### ISSUE TITLE
Generating load_data.csv and load_data_with_illum.csv for JUMP_production

### ISSUE THREAD

**Issue by sooheon** [broadinstitute/imaging-platform-pipelines#29]
The entrypoint to the pipelines starting from raw images appears to be `JUMP_illum_LoadData_v1.cpproj`, which generates illumination correction fn files, and then `JUMP_analysis_v3.cppipe` for the feature generation, which takes the images and ICF npy files as input.

Both these pipelines require a csv file containing filepaths and metadata. Is the expected format and metadata for this file (columns) documented anywhere, and are there any vendor specific scripts to automatically generate them from default exports?

The youtube [Headless CellProfiler/ DistributedCellProfiler Tutorial](https://www.youtube.com/watch?v=LuJxIGGhRek) references loading the images into CellProfiler by drag-n-drop and then exporting the file, but this is not convenient for distributed / cloud use case.

**Comment by bethac07** [comment]
Hi,

The expected format of these scripts is [here](https://cellprofiler-manual.s3.amazonaws.com/CellProfiler-4.2.5/modules/fileprocessing.html#loaddata). For PerkinElmer, we use a tool called [pe2loaddata](https://github.com/broadinstitute/pe2loaddata) to generate these CSVs, we do not have scripts for other manufacturers but it should be relatively straightforward for anyone comfortable coding since the specs are very simple. For the actual JUMP data itself, the CSVs are present within the workspace folder of each source on the Gallery, you need only unzip them.

Good luck!

**Comment by sooheon** [comment]
Perfect, thank you.
